### ISSUE TITLE
Update for 0.7

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/grunt-purescript#18]

**Comment by hdgarrood** [comment]
Perhaps in a week or two, if nobody complains too much about this not having been updated, it might make sense to deprecate this instead? I don't think we need three separate build tools: gulp-purescript and pulp ought to be enough, right?

**Comment by garyb** [comment]
Yeah, I don't have much enthusiasm for working on it as I don't use Grunt anymore, so I wouldn't mind that really. If people want it updating then I guess its worthwhile, but I don't think I've seen anyone specifically requiring it over gulp/pulp yet.

**Comment by garyb** [comment]
If anyone else wants to take over maintenance I'd be more than happy for that to happen too :wink:
